### ISSUE TITLE
Issues for demo

### ISSUE THREAD

**Issue by erasche** [TAMU-CPT/galaxy-apollo#2]
- [x] switch to genus + species
- [x] fetch all ref seqs
- [x] remove unused / unneeded functions

cc @nathandunn

**Comment by nathandunn** [comment]
👍  I'll add more as I think of them.

**Comment by nathandunn** [comment]
- [ ] remove unused / unneeded functions

**Comment by erasche** [comment]
Which unused/unneeded functions might those be? Everything in webapollo.py or ... ?

**Comment by nathandunn** [comment]
Hmm . . removing should be done from the tools side (renumbering, fix genes, etc) - so its not on the display.   Leaving the functionality is fine here.

**Comment by erasche** [comment]
Ah, I see what you are saying. Yes, definitely, agreed. Those tools do not need to be part of this distribution.

**Comment by erasche** [comment]
- [ ]  ensure that fetch/retrieve can accept a json list, if users want to fetch >1 organism. xref https://github.com/GMOD/Apollo/issues/1045#issuecomment-221466821

**Comment by nathandunn** [comment]
- [ ] FASTA includes "##FASTA" header at tail end.   On exporting two scaffolds the header is included in the tail of the first one as below.  Not sure if removing that from the [record] directly makes sense.  Looking at the [GFF3 Parsing code](https://github.com/chapmanb/bcbb/blob/master/gff/BCBio/GFF/GFFParser.py) seems to indicate that it should be handled, so not sure what is not being handled.  

```
TCACTCCGTCAC##FASTA
>ctgB
ACATGCT
```

**Comment by nathandunn** [comment]
FYI . . running through tests, though the GFF3 and FASTA seemed to be working properly (than otherwise noted).

**Comment by nathandunn** [comment]
I'm going to re-check the export. . . I'm actually seeing that its not exporting the GFF3 records properly (only a single feature of GFF3 is being exported) on one of the scaffolds and the feature data isn't showing up properly.  I **think** this has to do with garbage data, but I will double-check.   It should work for different types.  Will re-create this.

**Comment by nathandunn** [comment]
There is an issue exporting / annotating the GFF3, but this is due to something on the Apollo side, exporting data badly.

**Comment by nathandunn** [comment]
Referenced this issue: https://github.com/GMOD/Apollo/issues/1052

**Comment by erasche** [comment]
Making updates to the tools today, more generic interfaces / better support for the JSON files. etc. Will keep you posted.

**Comment by nathandunn** [comment]
Note: Cleaned out feature data by:

```
root@700dc7ee52d5:/# psql -U postgres 
psql (9.5.2)
Type "help" for help.

postgres=# delete from feature_grails_user  ;
DELETE 5
postgres=# delete from feature_relationship  ;
DELETE 5
postgres=# delete from feature_location ;     
DELETE 8
postgres=# delete from feature ;              
DELETE 8
```

**Comment by nathandunn** [comment]
👍    

Noted that the issue with export was running 2.0.2.   In https://github.com/erasche/docker-compose-galaxy-annotation  it looks like the image is still pointing to the older (2.0.2) Apollo.

**Comment by erasche** [comment]
Might try `TRUNCATE feature CASCADE;` in case that would work.

> looks like the image is still pointing to the older (2.0.2) Apollo

Can you trigger a re-build of `gmod/apollo:stable`?

**Comment by nathandunn** [comment]
@erasche  Good point I'll try that the truncate.   Retesting the build now.

**Comment by erasche** [comment]
@nathandunn you may have to manually re-trigger the build. https://hub.docker.com/r/gmod/apollo/tags/

**Comment by nathandunn** [comment]
Yeah, I will.  Ran into some other build issues.   Hopefully fixing shortly.

**Comment by erasche** [comment]
@nathandunn oh, just noticed it wasn't an automated build. Gotcha. No rush in that case.

**Comment by nathandunn** [comment]
I retagged it so I think the “latest” tag should be ready to test with. 

Nathan

**Comment by erasche** [comment]
@nathandunn what are you doing to get it to build? You're building from master, right?
Are you adjusting the apollo-config.groovy at all?

I need to switch user for bower (https://github.com/erasche/docker-webapollo2/commit/a5ca6b4b65ab06cdd515389aea177ec2a412d92f) but that isn't enough.

I still see

```
using bower to install: GMOD/jbrowse#tags/1.12.1-release
bower jbrowse#tags/1.12.1-release       not-cached git://github.com/GMOD/jbrowse.git#tags/1.12.1-release
bower jbrowse#tags/1.12.1-release          resolve git://github.com/GMOD/jbrowse.git#tags/1.12.1-release
bower jbrowse#tags/1.12.1-release     ENORESTARGET Tag/branch tags/1.12.1-release does not exist

Additional error details:
Available tags: 1.1-release, 1.10.0-release, 1.10.1-release, 1.10.10-release, 1.10.11-release, 1.10.12-release, 1.10.2-release, 1.10.3-release, 1.10.4-
release, 1.10.5-release, 1.10.6-release, 1.10.7-release, 1.10.8-release, 1.10.9-release, 1.11.0-release, 1.11.1-release, 1.11.2-release, 1.11.3-release
, 1.11.4-release, 1.11.5-release, 1.11.6-release, 1.12.0-release, 1.12.1-rc1, 1.12.1-rc2, 1.12.1-rc3, 1.12.1-release, 1.2-release, 1.2.1-release, 1.2.2
-release, 1.3.0-release, 1.3.1-release, 1.4.0-release, 1.4.1-release, 1.4.2-release, 1.5.0-release, 1.6.0-release, 1.6.1-release, 1.6.2-release, 1.6.3-
release, 1.6.4-release, 1.6.5-release, 1.7.0-release, 1.7.1-release, 1.7.2-release, 1.7.3-release, 1.7.4-release, 1.7.5-release, 1.7.6-release, 1.8.0-r
elease, 1.8.1-release, 1.9.0-release, 1.9.1-release, 1.9.2-release, 1.9.3-release, 1.9.4-release, 1.9.5-release, 1.9.6-release, 1.9.7-release, 1.9.8-re
lease
Available branches: 2.x, Eric_work_f1, Kevin-Mohamed-CollapseButton, Kevin-Mohamed-CollapseButton2, SVG-Track, SVG-Track-configurable, allow_multitype_
```

when trying to build.

**Comment by erasche** [comment]
NVM, fixed in master of apollo

**Comment by nathandunn** [comment]
*whew* I remembered fixing something like that.

**Comment by erasche** [comment]
Getting the list index out of range here too.

Investigating now...

**Comment by erasche** [comment]
Ok, ideally they should be fixed with latest version. Pushing now.

**Comment by nathandunn** [comment]
Everything else seems to be working.   There are some issues in annotating non-MRNA / Canvas, but I think that is an issue with Canvas + Apollo (see https://github.com/GMOD/Apollo/issues/1077) . . we'll have a fix for it soon I hope. 

I also had another issue when exporting annotations that are not mRNA, but I think that is an artifact as I don't see that anywhere else (and its definitely happening on the Apollo side).

**Comment by monicacecilia** [comment]
I tested and closed https://github.com/GMOD/Apollo/issues/1077 💃
