### ISSUE TITLE
Manual how to use galaxy-apollo

### ISSUE THREAD

**Issue by mictadlo** [TAMU-CPT/galaxy-apollo#6]
Hello,
By any chance, do you have a manual or youtube video how to use galaxy-apollo?

Thank you in advance.

Mic

**Comment by erasche** [comment]
Hi Mic,

Does http://gxaa.readthedocs.io/en/latest/doc/Apollo.html meet your needs?

Regards,
Eric

**Comment by mictadlo** [comment]
Thank you it looks good.

**Comment by nathandunn** [comment]
Hadn't seen the new doc.  Looks great 👍
