### ISSUE TITLE
Include caching code

### ISSUE THREAD

**Issue by erasche** [TAMU-CPT/galaxy-apollo#9]
@abretaud wanted to get your opinion on this before I implemented this for everyone :)

The tools are absurdly slow because the dynamic_options functions are called 5 times (each).

```
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:15 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:16 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:17 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:18 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:19 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:19 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:20 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:21 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:22 2017')
('TIME[REQUIRE_USER] = %s', 'Tue Jan 31 21:21:22 2017')
```

That's crazy. 7 seconds just to re-fetch

Thus, I'd like to include a cache. How do you feel about this? Even for a short timeout (e.g. 10 minutes is better than nothing.) Would you be worried about busting this cache or confused users?

**Comment by nathandunn** [comment]
@erasche   Curious .. is this Galaxy or Docker?

**Comment by erasche** [comment]
This is something galaxy does. They rerender the tool internally multiple times and abuse the heck out of the API, causing tools to take 7+ seconds to load.
